fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
      ref: '4.14.0'
    inifile:
      repo: 'git@github.com:puppetlabs/puppetlabs-inifile.git'
      ref: '1.6.0'
    remotefile:
      repo: 'git@github.com:lwf/puppet-remote_file.git'
      ref: 'v1.1.3'
  symlinks:
    gitea: "#{source_dir}"
